Finished header Component
jespernpedersen/dissertation-project pull request #48
Opened 2021-11-19 15:39 UTC by DiogoGeada

closes #35

2021-11-22 16:13 UTC, jespernpedersen requested changes

2021-11-22 16:13 UTC, jespernpedersen commented on src/components/headerComponent.vue
> +    data: () => ({}),
Don't include data if you are not using it.

2021-11-22 16:13 UTC, jespernpedersen commented on src/components/headerComponent.vue
> +            if(!this.banner) return "";
It should return a placeholder image instead if one isn't set.

2021-11-22 16:13 UTC, jespernpedersen commented on src/components/headerComponent.vue
> +    <header id="header">
Don't use id header for a tag that is already semantically header. Just use header or give it another name that is more specific to your usage of it.

2021-11-22 16:13 UTC, jespernpedersen commented on src/components/headerComponent.vue
> +
Remove empty space

2021-11-25 17:19 UTC, jespernpedersen requested changes

2021-11-25 17:19 UTC, jespernpedersen commented on src/components/Header.vue
> +        bannerStyle: {}
Data prop not being used.

2021-11-26 11:09 UTC, akram0171 approved these changes

2021-11-26 16:54 UTC, merged