Feature/#54
jespernpedersen/dissertation-project pull request #59
Opened 2021-11-29 12:33 UTC by akram0171

MockRestaurantService.js and restaurants.json

2021-11-29 20:40 UTC, jespernpedersen approved these changes

2021-11-30 10:18 UTC, DiogoGeada requested changes

2021-11-30 10:18 UTC, DiogoGeada commented on src/services/mockRestaurantService.js
> +export default class RestaurantsService {
Service names should be singular.

2021-11-30 10:41 UTC, DiogoGeada approved these changes

2021-11-30 10:42 UTC, merged