Feature/#84
jespernpedersen/dissertation-project pull request #93
Opened 2021-12-23 13:34 UTC by jespernpedersen

2021-12-23 22:18 UTC, akram0171 approved these changes

2021-12-27 11:21 UTC, DiogoGeada requested changes
You need to increase the space between the logos and titles, they are too close and look wierd.

![image](https://user-images.githubusercontent.com/18559792/147467035-1237bec7-e045-4669-b423-c8700d947752.png)

2021-12-27 11:21 UTC, DiogoGeada commented on tests/unit/restaurant.test.js
> +    const image = require('@/assets/images/All-American-Bacon-Cheeseburgers_exps48107_TH2379798C03_29_1b_RMS.jpg');
Jest doesn't work with images, so, you can just pass empty strings instead

2021-12-28 12:38 UTC, DiogoGeada approved these changes

2021-12-28 12:38 UTC, merged